name: Docker Image CI
run-name: Docker build Image - Go
on:
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${minor}.${major}.${patch}-${increment}"
        id: version

      - name: Install Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker buildx build \
            -f Dockerfile \
            -t ${{ secrets.DOCKER_USER }}/hello-world-go-training:${{ env.NEW_VERSION }} \
            --platform=linux/arm64,linux/amd64 .

      - name: Push the Docker Image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push ${{ secrets.DOCKER_USER }}/hello-world-go-training:${{ env.NEW_VERSION }}
